# Jacobi Method

In [4]:
# See all cell outputs in Jupyter (or iPython)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
import numpy as np

In [2]:
!pip install numpy

In [9]:
A = [1, 3, 4]
B = [0, 2, 3]
A-B

TypeError: unsupported operand type(s) for -: 'list' and 'list'

## Exemplos com NumPy

In [5]:
# Um vetor linha
A = np.array([1, 2, 3])
A
A.shape

array([1, 2, 3])

(3,)

In [15]:
AM = np.array([ [1, 2, 3] ])
AM
AM.shape

array([[1, 2, 3]])

(1, 3)

In [16]:
M = np.array([ [2, -3], [4, 5] ])
M
M.shape

array([[ 2, -3],
       [ 4,  5]])

(2, 2)

In [19]:
# Matriz Coluna
P = np.array([ [-1], [2], [3] ])
P
P.shape

array([[-1],
       [ 2],
       [ 3]])

(3, 1)

In [27]:
P = np.array([ [-1, 2, 3] ])
P.T

array([[-1],
       [ 2],
       [ 3]])

In [29]:
A = np.array([ [10, 20] ])
B = np.array([ [3, 4] ])

A+B
A-B
A*B # !!! Não é o produto matricial, é o produto elemento a elemento
A.dot(B.T) # É o produto matricial da matriz A pela trasposta da matriz B

array([[13, 24]])

array([[ 7, 16]])

array([[30, 80]])

array([[110]])

# Aula 06 - 29/10

In [6]:
A = np.array([ [2, 3, 4], [-1, 2, 0] ])
A

array([[ 2,  3,  4],
       [-1,  2,  0]])

In [7]:
A.T # Matriz transposta de A

array([[ 2, -1],
       [ 3,  2],
       [ 4,  0]])

In [8]:
# Como calcular a matriz inversa com o NumPy
B = np.array( [ [1, 2], [-1, 4] ] )
B
np.linalg.inv(B) # Matriz inversa de B

C = np.array( [ [2, 3], [1, -1] ] )
C

array([[ 1,  2],
       [-1,  4]])

array([[ 0.66666667, -0.33333333],
       [ 0.16666667,  0.16666667]])

array([[ 2,  3],
       [ 1, -1]])

In [11]:
B+C
B-C
B*C # Não é a multiplicação de matrizes (multiplicação matricial), é a multiplicação elemento a elemento

array([[3, 5],
       [0, 3]])

array([[-1, -1],
       [-2,  5]])

array([[ 2,  6],
       [-1, -4]])

In [12]:
# Multiplicação de Matrizes (multiplicação matricial) (não é comutativo)
B.dot(C)
C.dot(B)

array([[ 4,  1],
       [ 2, -7]])

array([[-1, 16],
       [ 2, -2]])

In [9]:
# Função auxiliar Decompose (decompõe a matrix A em uma matriz diagonal D e uma matriz não-diagonal N)
def Decompose(A):
    # Inicialmente criamos D e N como matrizes nulas com o mesmo tamanho da matriz A
    D = np.zeros(np.shape(A))
    N = np.zeros(np.shape(A))
    
    for i in range(len(A)):
        for j in range(len(A)):
            if i==j:
               D[i,j] = A[i,j]
            else:
                N[i,j] = A[i,j]
    
    return D, N

In [10]:
C = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
C
D, N = Decompose(C)
D
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

array([[0., 2., 3.],
       [4., 0., 6.],
       [7., 8., 0.]])

In [11]:
# Teste para fazer a função Inversa
A
np.zeros(A.shape)

array([[ 2,  3,  4],
       [-1,  2,  0]])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# Função auxiliar para calcular a inversa de uma matriz
def Inversa(M):
    # Iniciamos M_Inv como uma matriz de zeros do mesmo tamanho que M
    M_Inv = np.zeros(M.shape)
    
    for i in range(len(M)):
        M_Inv[i,i] = 1/M[i, i]
    
    return M_Inv

In [31]:
D = np.array( [ [1, 0, 0], [0, 2, 0], [0, 0, 3] ])
D
Inversa(D)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

array([[1.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.33333333]])

In [13]:
def Jacobi(A, B, X, tol, max_iter):
    # Garantimos que os argumentos/parâmetros são objetos NumPy Array
    A = np.array(A)
    B = np.array(B)
    X = np.array(X)
    
    # Decompor A em duas matrizes
    D, N = Decompose(A)
    
    # Calculamos a inversa de D
    D1 = Inversa(D)
    
    # Definimos a função G
    def G(X):
        # D-1(B-NX)
        return D1.dot(B-N.dot(X))
    
    # Algoritmo do ponto fixo
    # Obtemos o novo ponto X
    X1 = G(X)

    # Calculamos o tamanho da diferença entre as duas soluções
    norm = np.linalg.norm(X1-X)
    
    n = 1
    while norm > tol and n < max_iter:
        # Swap das variáveis
        # Nesta iteração o X1 (atual) vai passar a ser o antigo (X)
        X = X1
        
        # Calculamos o novo X
        X1 = G(X)
        
        # Calculamos a nova distância entre os pontos (nova norma)
        norm = np.linalg.norm(X1-X)
        
        # Incrementamos o novo contador
        n += 1
    
    print(f"Num. iterações {n}")
    
    return X1

In [14]:
A1 = [ [3, 1], [1, 1]]
B1 = [ [-3], [3] ]
X = [ [1], [1] ]

Jacobi(A1, B1, X, 0.00001, 100)

Num. iterações 25


array([[-2.99999686],
       [ 5.99999247]])

In [15]:
A2 = [ [1, 3], [1, 1]]

Jacobi(A2, B1, X, 0.001, 100)

Num. iterações 100


array([[-3.58948994e+24],
       [ 2.87159195e+24]])