# Jacobi Method

In [1]:
# See all cell outputs in Jupyter (or iPython)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [11]:
import numpy as np

In [8]:
!pip install numpy

In [9]:
A = [1, 3, 4]
B = [0, 2, 3]
A-B

TypeError: unsupported operand type(s) for -: 'list' and 'list'

## Exemplos com NumPy

In [14]:
# Um vetor linha
A = np.array([1, 2, 3])
A
A.shape

array([1, 2, 3])

(3,)

In [15]:
AM = np.array([ [1, 2, 3] ])
AM
AM.shape

array([[1, 2, 3]])

(1, 3)

In [16]:
M = np.array([ [2, -3], [4, 5] ])
M
M.shape

array([[ 2, -3],
       [ 4,  5]])

(2, 2)

In [19]:
# Matriz Coluna
P = np.array([ [-1], [2], [3] ])
P
P.shape

array([[-1],
       [ 2],
       [ 3]])

(3, 1)

In [27]:
P = np.array([ [-1, 2, 3] ])
P.T

array([[-1],
       [ 2],
       [ 3]])

In [29]:
A = np.array([ [10, 20] ])
B = np.array([ [3, 4] ])

A+B
A-B
A*B # !!! Não é o produto matricial, é o produto elemento a elemento
A.dot(B.T) # É o produto matricial da matriz A pela trasposta da matriz B

array([[13, 24]])

array([[ 7, 16]])

array([[30, 80]])

array([[110]])