# Jacobi Method

* The Jacobi method is an iterative algorithm for determining the solutions of a system of linear equations.
* The system must be diagonally dominant.
  https://en.wikipedia.org/wiki/Diagonally_dominant_matrix
* The general algorithm follows the same structure as the fixed-point method studied earlier.

In [1]:
# See all cell outputs in Jupyter (or iPython)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
# Se for preciso instalar NumPy corra o código abaixo
# !pip install numpy

In [4]:
from math import sqrt
import numpy as np

## NumPy Examples

In [6]:
# Criar uma matrix
# !!! Vamos utilizar sempre listas de listas para garantir um array 2D (uma Matriz) !!!

A_Vector = np.array( [3] )
A_Matriz = np.array( [[3]] )
B = np.array( [ [1, 2] ] )
C = np.array( [ [1, 2], [3,4], [4, 5] ] )

In [7]:
A_Vector
A_Vector.shape
A_Matriz
A_Matriz.shape

array([3])

(1,)

array([[3]])

(1, 1)

In [10]:
B
B.shape
C
C.shape

array([[1, 2]])

(1, 2)

array([[1, 2],
       [3, 4],
       [4, 5]])

(3, 2)

In [11]:
# A magnitude ou norma de um vector é

A = np.array([[10]])    # norma = 10
B = np.array([[3, 4]])  # norma = sqrt(3^2 + 4^2) = 5

np.linalg.norm(A)
np.linalg.norm(B)

10.0

5.0

In [12]:
# Para as operações de soma, subtração, e multiplicação (elemento a elemento)
# não precisamos de invocar um método, podemos utilizar os operadores convencionais

A = np.array([[10, 20]])
B = np.array([[3, 4]])

A+B
A-B
A*B # !!! Não é o produto de matrices. É o produto elemento a elemento !!!

array([[13, 24]])

array([[ 7, 16]])

array([[30, 80]])

In [13]:
# Para o produto matricial temos que utilizar um método

A = np.array([[1, 2], [0, 4]])
# A = | 1  2 |
#     | 0  4 |

B = np.array([[10], [20]])
# B = | 10 |
#     | 20 |

A.dot(B)
#or
np.dot(A, B)

array([[50],
       [80]])

array([[50],
       [80]])

In [14]:
# Para calcular a inversa de uma matriz
A = np.array([[1, 2], [0, 4]])
# A = | 1  2 |
#     | 0  4 |

A1 = np.linalg.inv(A)
A1

# Verificação
A.dot(A1) # Matriz identidade

array([[ 1.  , -0.5 ],
       [ 0.  ,  0.25]])

array([[1., 0.],
       [0., 1.]])

In [15]:
# Contudo nós vamos definir a nossa própia função para calcular a inversa de uma matriz diagonal

def Inverse(M):
    """
    Determina a inversa da matriz diagonal M
    defininida como NumPy Array 
    """
    
    # Iniciamos M_Inv como uma matriz de zeros do mesmo tamanho que M
    M_Inv = np.zeros(M.shape)
    
    # A inversa de uma matriz diagonal M é uma matriz diagonal contendo os reciprocos de M
    for i in range(len(M)):
        M_Inv[i,i] = 1/M[i,i]
    
    return M_Inv

In [16]:
D = np.array( [ [1, 0, 0], [0, 2, 0], [0, 0, 3] ])
D
Inverse(D)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

array([[1.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.33333333]])

In [17]:
# Também vamos precisar de descompor a matriz A em D+N

def Decompose(A):
    """
    Dada a matriz A (numpy array) devolve D e N.
    D: matriz diagonal obtida dos elementos da diagonal de A.
    N: matriz obtida com os elementos não diagonais de A e zero na diagonal.
    """
    
    # Inicialmente criamos D e N como uma matriz nula do mesmo tamanho que A
    D = np.zeros(A.shape)
    N = np.zeros(A.shape)
    
    for i in range(len(A)):
        for j in range(len(A)):
            if i==j:
                D[i,j] = A[i,j]
            else:
                N[i,j] = A[i,j]
    
    return D, N

In [19]:
A=np.array( [ [1, 2, 3], [4, 5, 6], [7, 8, 9]  ] )
A
D, N = Decompose(A)
D
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

array([[0., 2., 3.],
       [4., 0., 6.],
       [7., 8., 0.]])

## Example systems

**System 1**

3x<sub>1</sub> + x<sub>2</sub> = -3  
&nbsp;&nbsp;x<sub>1</sub> + x<sub>2</sub> = 3

Solution: x<sub>1</sub>=-3 e x<sub>2</sub>=6

**System 2**

* In this system, we just swap the columns of the previous system.
* So, the solutions must be the same.
* However, the system is not longer diagonally dominant.


x<sub>2</sub> + 3x<sub>1</sub> = -3  
x<sub>2</sub> + &nbsp;&nbsp;x<sub>1</sub> = 3

In [20]:
# System 1

A1 = np.array([ [3, 1], [1, 1] ])
B1 = np.array([[-3, 3]]).T   # T de transposta para obter um vector coluna
A1
B1

array([[3, 1],
       [1, 1]])

array([[-3],
       [ 3]])

In [21]:
# System 2
A2 = np.array([ [1, 3], [1, 1] ])
B2 = B1
A2
B2

array([[1, 3],
       [1, 1]])

array([[-3],
       [ 3]])

## Implementação utilizando NumPy

Using NumPy's capabilities to work with matrices, we can implement Jacobi's method following the structure of the fixed-point method.

In [22]:
def JacobiNumPy(A, B, X0, tol, max_iter):
    """
     A: Matriz dos coeficientes das variáveis
     B: Matriz dos termos independentes
    X0: Solução inicial aproximada
    """
    
    # Garantimos que os argumentos são objectos NumPy Array
    A  = np.array(A)
    B  = np.array(B)
    X0 = np.array(X0)

    # Decompomos a matriz A em dois matrices
    D, N = Decompose(A)
    
    # Vamos sempre a trabalhar com a inversa de D
    # Por isso a calculamos agora
    D1 = Inverse(D)
    
    # Função auxiliar para calcular cada novo vector
    # TÊM QUE PERCEBER COM OBTER ESTA FORMULA
    # g = D^(-1)*(B-N*X0)
    def g(X0):
        return D1.dot(B-N.dot(X0))
    
    # O ponto seguinte é obtido evaluando g
    X1 = g(X0)
    
    # Calculamos o tamanho da diferença entre as duas soluções
    norm = np.linalg.norm(X1-X0)
    
    n=1
    while norm>tol and n<max_iter:
        
        # O X actual (X1) vai passar a ser o antigo (X0)
        X0 = X1
        
        # Calculamos o novo X
        X1 = g(X0)
        
        norm = np.linalg.norm(X1-X0)
        n += 1
        
    print(f"Num. iteractions {n}")
    
    return X1

In [23]:
# Resolvendo o sistema 1

# Utilizando X0 = [1, 1]
# A solução é [-3, 6]

X0 = np.array([[1, 1]]).T

JacobiNumPy(A1, B1, X0, 0.001, 100)

Num. iteractions 17


array([[-2.99974597],
       [ 5.99939034]])

In [24]:
# Resolvendo o sistema 2

# Utilizando X0 = [1, 1]
# A solução é [6, -3]

JacobiNumPy(A2, B2, X0, 0.001, 100)

Num. iteractions 100


array([[-3.58948994e+24],
       [ 2.87159195e+24]])

## Implementation in pure Python

In [25]:
def Subtract(A, B):
    """Calcula A-B"""
    
    D = []
    for i in range(len(A)):
        D.append(A[i]-B[i])
    return D

In [26]:
Subtract([1],[3])          # -2
Subtract( [2, 4], [1, 3] ) # [1, 1]

[-2]

[1, 1]

In [27]:
def Norm(A):
    """Calcula a magnitude ou norma do vector A"""
    
    soma = 0
    for i in range(len(A)):
        soma += A[i]**2
    return sqrt(soma)

In [28]:
Norm([10])    # 10
Norm([3, 4])  # 5

10.0

5.0

In [29]:
def JacobiPython(A, B, X0, tol, max_iter):
    
    # Criamos uma lista para conter as souluções
    # Vai ser inicialmente igual à lista de soluções proposta x0
    X = X0.copy()
    
    # Quantidade de variveis e equações
    m = len(X)
    
    # Iniciamos o contador de iterações
    n = 0
    norm=tol+1
    while norm>tol and n<=max_iter:
        for i in range(m):
            
            soma = 0
            for j in range(m):
                if i!=j:
                    soma += A[i][j]*X[j]
            
            X[i] = 1/A[i][i]*(B[i]-soma)       
     
        norm = Norm(Subtract(X, X0))
        X0 = X.copy()
        n += 1
        
    print(f"Num. iteractions {n}")
    
    return X

In [30]:
# System 1 using lists
# Solution [-3, 6]

A = [ [3, 1], [1, 1] ]
B = [-3, 3]
X = [1, 1]

In [31]:
JacobiPython(A, B, X, 0.001, 100)

Num. iteractions 9


[-2.999745973682873, 5.999745973682873]